# We could create a script to help automate github workflow? it would basically be like vscode's git panel integration!

# - linux watch fs [~/Wiki]()
# - Commit message auto-generated?
# - Changelog autogenerated?
# - Commit action never be automated!